### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by huglester** [lawrencebensaid/enet-api#1]
Hello

node src/main.js auth admin admin 192.168.1.5

gives error:
Error: undefined

maybe you got some suggestions?

**Comment by huglester** [comment]
this is very strange. But after some time, I now get "Authentication successful"

any idea what is happening over here?

**Comment by lawrencebensaid** [comment]
Without an error it is hard to say. Try using the `--debug` flag when running the command:

`$ enet -d auth admin admin 192.168.1.5`

**Comment by huglester** [comment]
Hi. with most recent version it works without problems. (auth, device ls - at least)
